from django.conf.urls import patterns, url
from warehouse.views import reports

urlpatterns = patterns('',
                       url(r'^$', 'warehouse.views.index', name='warehouse-index'),

                       # url haaye marbut be havaleehaye jadid ham va3 anbaardar ham va3 deliveryman
                       url(r'^NewOrder$', 'warehouse.views.new_order', name='WRH_New_Orders'),
                       url(r'^OrdersPanel$', 'warehouse.views.order_panel', name='WRH_New_Orders_Panel'),
                       url(r'^ReadyOrder$', 'warehouse.views.ready_order', name='WRH_Ready_Orders'),
                       url(r'^OrdersReadyPanel$', 'warehouse.views.ready_order_panel', name='WRH_Ready_Orders_Panel'),
                       url(r'^ConfirmOrder/(?P<pid>\d+)$', 'warehouse.views.confirm_order',
                           name='WRH_Confirm_New_Orders'),
                       url(r'^ConfirmReadyOrder/(?P<pid>\d+)$', 'warehouse.views.confirm_ready_order',
                           name='WRH_Confirm_Ready_Order'),

                       #url haaye marbut be sabte vorude kalaa be anbaar
                       url(r'^WRHDelivery$', 'warehouse.views.delivery_wiki_select', name='WRH_Delivery'),
                       url(r'^WRHDelivery-Panel$', 'warehouse.views.delivery_wiki_select_panel', name='WRH_Delivery_Panel'),
                       url(r'^WRHDeliveryConfirmation$', 'warehouse.views.confirm_wrh_delivery',
                           name='WRH_Delivery_Confirm'),
                       url(r'^WRHDelivery-next/(?P<pid>\d+)$', 'warehouse.views.delivery_product_select',
                           name='WRH_Delivery_Next'),

                       #url haaye marbut be bargashte kaalaaye mayoub az moshtari
                       url(r'^CustomerReturn$', 'warehouse.views.customer_return', name='WRH_Customer_Return'),
                       url(r'^CustomerReturn-Panel$', 'warehouse.views.customer_return_panel', name='WRH_Customer_Return_Panel'),
                       url(r'^CustomerReturn-next$', 'warehouse.views.customer_return_next',
                           name='WRH_Customer_Return_Next'),
                       url(r'^CustomerReturn-next/(?P<pid>\d+)/(?P<kid>\d+)$', 'warehouse.views.customer_return_next2',
                           name='WRH_Customer_Return_Next2'),
                       url(r'^ConfirmReturn/(?P<pid>\d+)/(?P<kid>\d+)/(?P<cid>\d+)/(?P<type>\S+)$', 'warehouse.views.confirm_return',
                           name='WRH_Confirm_Return'),

                       #url haaye marbut be reside kalaahaaye havale be moshtari ya wiki
                       url(r'^Cust-wiki-ReceiptDelivery$', 'warehouse.views.ReceiptDelivery', name='WRH_Cust_Wiki_Receipt_Delivery'),
                       url(r'^Cust-wiki-ReceiptDelivery-Panel$', 'warehouse.views.ReceiptDelivery_Panel', name='WRH_Cust_Wiki_Receipt_Delivery_Panel'),
                       url(r'^ReceiptDetail$', 'warehouse.views.receipt_detail',
                           name='WRH_Receipt_Detail'),
                       url(r'^ConfirmReceipt/(?P<pid>\d+)$', 'warehouse.views.confirm_receipt',
                           name='WRH_Confirm_Receipt'),

                       #url marbut be report haa
                       url(r'^Report/(?P<menu_id>\d+)$', 'warehouse.views.reports',
                           name='WRH_Report'),
                       url(r'^ReportReceipt_Panel/(?P<menu_id>\d+)$', 'warehouse.views.report_receipt_panel',
                           name='WRH_Report_Receipt_Panel'),
                       url(r'^WRHgardani-Panel$', 'warehouse.views.wrh_gardaani',
                           name='WRH_Gardaani_Panel'),
                       url(r'^Print$', 'warehouse.views.printt',
                           name='WRH_Print'),
                       url(r'^PrintDif$', 'warehouse.views.print_dif',
                           name='WRH_PrintDif'),
                       url(r'^PrintCustomerReceipt/(?P<clr_id>\d+)$', 'warehouse.views.print_customer_receipt',
                           name='WRH_Print_Customer_Receipt'),
                       url(r'^PrintWikiReceipt/(?P<clr_id>\d+)$', 'warehouse.views.print_wiki_receipt',
                           name='WRH_Print_Wiki_Receipt'),
                       url(r'^PrintWikiReturn/(?P<clr_id>\d+)$', 'warehouse.views.print_wiki',
                           name='WRH_Wiki_Return'),
                       url(r'^PrintStock$', 'warehouse.views.print_stock',
                           name='WRH_Print_Stock'),
                       url(r'^PrintDamaged$', 'warehouse.views.print_damaged',
                           name='WRH_Print_Damaged'),
                        url(r'^PrintWikiOrders$', 'warehouse.views.print_wiki_order',
                            name='WRH_Print_Wiki_Orders'),
                        url(r'^WRHPrintDelivery$', 'warehouse.views.print_wrh_delivery',
                            name='WRH_Print_Delivery'),
                        url(r'^PrintClear$', 'warehouse.views.print_wrh_clear',
                            name='WRH_Print_Clear'),
                        url(r'^PrintCustRcpt$', 'warehouse.views.print_custrcpt',
                            name='WRH_Print_CustRcpt'),
                        url(r'^PrinWikiRcp$', 'warehouse.views.print_WikiRcp',
                            name='WRH_Print_WikiRcpt'),
                        url(r'^PrintHvl$', 'warehouse.views.print_Hvl',
                            name='WRH_Print_Hvl'),
                       url(r'^WRHGardaniConfirmation$', 'warehouse.views.wrh_gardaani_confirm',
                           name='WRH_Gardaani_Confirm'),
                       # url(r'^(?P<org>\S+)ReportReceipt_Panel/(?P<menu_id>\d+)?page=(?P<num>\d+)$', 'warehouse.views.report_receipt_panel',
                       #     name='warehouse-index-tiny_order'),
                       url(r'^ReportProduct_Panel/(?P<menu_id>\d+)$', 'warehouse.views.report_product_panel',
                           name='WRH_Report_Product_Panel'),
                       url(r'^ReportProduct_Panel/(?P<menu_id>\d+)?page=(?P<num>\d+)$', 'warehouse.views.report_product_panel',
                           name='WRH_Report_Product_Panel'),

                       url(r'^ReportReceiptDelivery$', 'warehouse.views.report_receipt_delivery',
                           name='WRH_Report_Receipt_Delivery'),
                       url(r'^ReportReceiptDelivery_Panel$', 'warehouse.views.report_receipt_delivery2',
                           name='WRH_Report_Receipt_Delivery_Panel'),
                       url(r'^ReportReceiptDelivery_Panel?page=(?P<num>\d+)$$', 'warehouse.views.report_receipt_delivery2',
                           name='warehouse-index-test'),

                       url(r'^ReportReceiptNotDelivery$', 'warehouse.views.report_receipt_delivery_not',
                           name='WRH_Report_Receipt_Delivery_Not'),
                       url(r'^ReportReceiptNotDelivery_Panel$', 'warehouse.views.report_receipt_delivery_not2',
                           name='WRH_Report_Receipt_Delivery_Panel_Not'),
                       url(r'^ReportReceiptDelivery_Panel?page=(?P<num>\d+)$$', 'warehouse.views.report_receipt_delivery_not2',
                           name='warehouse-index-test'),

                       url(r'^ReportDetail/(?P<pid>\d+)/(?P<kid>\d+)$', 'warehouse.views.report_detail',
                           name='WRH_Report_Detail'),


                       #url haaye marbut be taghire noghteye sefaresh
                       url(r'^OrderPoint$', 'warehouse.views.point_order', name='WRH_Order_Point'),
                       url(r'^OrderPoint-Panel$', 'warehouse.views.point_orders_panel', name='WRH_Order_Point_Panel'),
                       url(r'^OrderPoint-next$', 'warehouse.views.point_order_next',
                           name='WRH_Order_Point_Next'),
                       url(r'^OrderPoint-next/(?P<kid>\d+)$', 'warehouse.views.point_order_next2',
                           name='WRH_Order_Point_Next2'),
                       url(r'^ConfirmOrderPoint/(?P<kid>\d+)/(?P<cid>\d+)$', 'warehouse.views.confirm_order_point',
                           name='WRH_Confirm_Order_Point'),

)
